export const FETCH_POKEMONS_START = 'FETCH_POKEMONS_START'
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS'
export const FETCH_POKEMONS_ERROR = 'FETCH_POKEMONS_ERROR'

export const LOAD_MORE_POKEMONS = 'LOAD_MORE_POKEMONS'
export const LOAD_MORE_ERROR = 'LOAD_MORE_ERROR'

export const SHOW_ITEM_START = 'SHOW_ITEM_START'
export const SHOW_ITEM_SUCCESS = 'SHOW_ITEM_SUCCESS'
export const SHOW_ITEM_ERROR = 'SHOW_ITEM_ERROR'

export const FILTER_ITEM_SUCCESS = 'FILTER_ITEM_SUCCESS'
export const FILTER_ITEM_ERROR = 'FILTER_ITEM_ERROR'

export const GET_TYPES_START = 'GET_TYPES_START'
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS'
export const GET_TYPES_ERROR = 'GET_TYPES_ERROR'
